version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - mkdir dist
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
